name: On a pull request on new MDI version

on:
  schedule:
  - cron: '0 0 * * *'

jobs:
  check_availability:

    runs-on: ubuntu-latest
    
    steps:
    # Get default & light libraries latest version
    - name: Get libraries latest version
      id: fetch_versions
      outputs:
      - mdi_default_version
      - mdi_light_version
      - mdip_default_version
      - mdip_light_version
      shell: python
      run: |
        import requests, json
        
        def get_package_json(name):
          package_json_s = requests.get('https://raw.githubusercontent.com/'+name+'/master/package.json').content
          return json.loads(package_json_s)
        
        def set_output(name, value):
          print('::set-output name={}::{}'.format(name, value))
        
        # Download & parse manifests
        mdi_default_version = get_package_json('Templarian/MaterialDesign-SVG')['version']
        mdi_light_version = get_package_json('Templarian/MaterialDesignLight-SVG')['version']
        mdip_default_version = get_package_json('Templarian/MaterialDesign-SVG')['materialdesignicons-picker']['version']['default']
        mdip_light_version = get_package_json('Templarian/MaterialDesignLight-SVG')['materialdesignicons-picker']['version']['light']
        
        set_output('mdi_default_version', mdi_default_version)
        set_output('mdi_light_version', mdi_light_version)
        set_output('mdip_default_version', mdip_default_version)
        set_output('mdip_light_version', mdip_light_version)
   
    
    # If they are different, open a PR
    - name: Open a PR
      if: steps.fetch_versions.outputs.mdi_default_version != steps.fetch_versions.outputs.mdip_default_version || steps.fetch_versions.outputs.mdi_light_version != steps.fetch_versions.outputs.mdi_light_version
      run: echo "TODO"
