name: On a pull request on new MDI version

on:
  schedule:
  - cron: '14 * * * *'

jobs:
  check_availability:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    # yarn install
    - run: yarn install && cd tools/github-actions/open-pr-on-new-mdi-version && yarn install

    # Check requirements: if there is a new version number,
    - name: PR checks & prerequisites
      id: prerequisites
      run: node tools/github-actions/open-pr-on-new-mdi-version/prepare-pr.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

    # Once manifest is updated, open a PR
    - name: Open a PR
      uses: peter-evans/create-pull-request@v1.1.3
      id: open_pr
      if: steps.prerequisites.outputs.proceed == 'yes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        PULL_REQUEST_BRANCH: "${{ format('auto-update-{0}', steps.prerequisites.outputs.mdi_upstream_default) }}"
        COMMIT_MESSAGE: "${{ format('package.json: update MDI versions (default: {0}, light: {1})', steps.prerequisites.outputs.mdi_upstream_default, steps.prerequisites.outputs.mdi_upstream_light) }}"
        PULL_REQUEST_TITLE: "${{ format('Upgrade MDI version (default: {0}, light: {1})', steps.prerequisites.outputs.mdi_upstream_default, steps.prerequisites.outputs.mdi_upstream_light) }}"
        PULL_REQUEST_BODY: "${{ format('Merge this PR to automatically release a new version of this extension, featuring up-to-date versions of the MaterialDesignIcons libraries (default: {0}, light: {1})', steps.prerequisites.outputs.mdi_upstream_default, steps.prerequisites.outputs.mdi_upstream_light) }}"
